In [91]:
from hmmlearn import hmm
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np 
from sklearn.model_selection import train_test_split
import spacy

nlp = spacy.load("en_core_web_sm")


In [92]:
data = pd.read_csv('ner_dataset.csv' , encoding='unicode_escape') 

In [93]:
preprocessed_data = data[['Word', 'Tag']]

In [94]:
word_encoder = LabelEncoder()
pos_encoder = LabelEncoder()

In [95]:
preprocessed_data['Word'] = word_encoder.fit_transform(preprocessed_data['Word'])
preprocessed_data['POS'] = pos_encoder.fit_transform(preprocessed_data['Tag'])

C:\Users\aniru\AppData\Local\Temp\ipykernel_6284\3112701486.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preprocessed_data['Word'] = word_encoder.fit_transform(preprocessed_data['Word'])
C:\Users\aniru\AppData\Local\Temp\ipykernel_6284\3112701486.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  preprocessed_data['POS'] = pos_encoder.fit_transform(preprocessed_data['Tag'])


In [96]:
num_states = 5
num_features = 2  

model = hmm.MultinomialHMM(n_components=num_states, n_iter=100)

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


In [97]:
X = preprocessed_data[['Word', 'POS']]
lengths = [len(preprocessed_data)]

model.fit(X, lengths)

MultinomialHMM(n_components=10, n_iter=100,
               n_trials=array([15092, 27715, 20984, ..., 33479, 33261, 17879]),
               random_state=RandomState(MT19937) at 0x1EA7F215D40)

In [98]:
predicted_labels = model.predict(X)

In [99]:
predicted_tags = pos_encoder.inverse_transform(predicted_labels)

In [100]:
preprocessed_data['Predicted_Tag'] = predicted_tags

In [101]:
print(preprocessed_data.head())

    Word Tag  POS Predicted_Tag
0  15076   O   16         B-art
1  27699   O   16         B-art
2  20968   O   16         B-art
3  24217   O   16         B-art
4  26433   O   16         B-art


In [102]:
transition_probs = model.transmat_ 
emission_probs = model.emissionprob_  
initial_probs = model.startprob_  

In [103]:
transition_probs

array([[8.62287434e-001, 8.49744845e-005, 2.68500096e-003,
        2.62639874e-060, 3.68267471e-003, 2.10552589e-002,
        7.30601267e-002, 1.46383061e-002, 2.12428530e-002,
        1.26337083e-003],
       [9.89587250e-001, 1.38247844e-005, 1.78289602e-004,
        2.74962530e-088, 2.77732868e-015, 6.45544736e-004,
        4.30276320e-003, 5.07554342e-003, 8.06567096e-010,
        1.96783882e-004],
       [8.54368327e-001, 4.88940907e-003, 5.99064878e-003,
        2.72837034e-087, 1.20477923e-079, 2.71742822e-003,
        9.82754220e-003, 6.13373329e-003, 1.14575932e-001,
        1.49697945e-003],
       [8.86568672e-001, 6.08404899e-004, 1.52620032e-006,
        1.39159156e-072, 2.62573604e-124, 3.16909719e-002,
        8.03362639e-002, 4.23219439e-020, 7.94160733e-004,
        5.13517276e-250],
       [8.20642129e-001, 1.04164488e-007, 9.16106243e-114,
        2.10450005e-002, 0.00000000e+000, 7.39841281e-002,
        7.17640368e-002, 1.47070529e-003, 1.10938965e-002,
        1.5

In [104]:
emission_probs

array([[9.99395452e-01, 6.04547840e-04],
       [5.69308254e-01, 4.30691746e-01],
       [5.96202334e-02, 9.40379767e-01],
       [2.29159741e-01, 7.70840259e-01],
       [9.52278411e-01, 4.77215892e-02],
       [5.95764057e-01, 4.04235943e-01],
       [5.75137707e-01, 4.24862293e-01],
       [9.91768157e-01, 8.23184255e-03],
       [9.97915946e-01, 2.08405424e-03],
       [1.91332723e-01, 8.08667277e-01]])

In [105]:
initial_probs

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [106]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("my name is aniruth")
named_entities = [(ent.text, ent.label_) for ent in doc.ents]
